edition = "2021"
force_explicit_abi = true
hard_tabs = false
imports_granularity = "Crate"
max_width = 100
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
